/* Generated by Yosys 0.57+72 (git sha1 fa02d71f6, x86_64-conda-linux-gnu-c++ 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/home/runner/work/conda-opensource-eda/conda-opensource-eda/workdir/conda-env/conda-bld/yosys_1757723646908/work=/usr/local/src/conda/yosys-0.57_73_gfa02d71f6 -fdebug-prefix-map=/home/admin/conda/envs/py313=/usr/local/src/conda-prefix -fPIC -O3) */

module croc_culp_chip(clk_i, rst_ni, ref_clk_i, jtag_tck_i, jtag_trst_ni, jtag_tms_i, jtag_tdi_i, jtag_tdo_o, uart_rx_i, uart_tx_o, fetch_en_i, status_o, gpio0_io, gpio1_io, gpio2_io, gpio3_io, gpio4_io, gpio5_io, gpio6_io, gpio7_io, gpio8_io
, gpio9_io, gpio10_io, gpio11_io, gpio12_io, gpio13_io, gpio14_io, gpio15_io, pll_clk_o, osc_clk_i);
  input clk_i;
  wire clk_i;
  input rst_ni;
  wire rst_ni;
  input ref_clk_i;
  wire ref_clk_i;
  input jtag_tck_i;
  wire jtag_tck_i;
  input jtag_trst_ni;
  wire jtag_trst_ni;
  input jtag_tms_i;
  wire jtag_tms_i;
  input jtag_tdi_i;
  wire jtag_tdi_i;
  output jtag_tdo_o;
  wire jtag_tdo_o;
  input uart_rx_i;
  wire uart_rx_i;
  output uart_tx_o;
  wire uart_tx_o;
  input fetch_en_i;
  wire fetch_en_i;
  output status_o;
  wire status_o;
  inout gpio0_io;
  wire gpio0_io;
  inout gpio1_io;
  wire gpio1_io;
  inout gpio2_io;
  wire gpio2_io;
  inout gpio3_io;
  wire gpio3_io;
  inout gpio4_io;
  wire gpio4_io;
  inout gpio5_io;
  wire gpio5_io;
  inout gpio6_io;
  wire gpio6_io;
  inout gpio7_io;
  wire gpio7_io;
  inout gpio8_io;
  wire gpio8_io;
  inout gpio9_io;
  wire gpio9_io;
  inout gpio10_io;
  wire gpio10_io;
  inout gpio11_io;
  wire gpio11_io;
  inout gpio12_io;
  wire gpio12_io;
  inout gpio13_io;
  wire gpio13_io;
  inout gpio14_io;
  wire gpio14_io;
  inout gpio15_io;
  wire gpio15_io;
  output pll_clk_o;
  wire pll_clk_o;
  input osc_clk_i;
  wire osc_clk_i;
  wire _00_;
  wire _01_;
  wire VDD;
  wire VSS;
  wire adc_inn_i;
  wire adc_inp_i;
  wire dac_outn_o;
  wire dac_outp_o;
  wire dac_vbias_i;
  wire pll_clk_dummy;
  wire soc_clk_i;
  wire soc_fetch_en_i;
  wire soc_gpio_en_o_0_;
  wire soc_gpio_en_o_10_;
  wire soc_gpio_en_o_11_;
  wire soc_gpio_en_o_12_;
  wire soc_gpio_en_o_13_;
  wire soc_gpio_en_o_14_;
  wire soc_gpio_en_o_15_;
  wire soc_gpio_en_o_1_;
  wire soc_gpio_en_o_2_;
  wire soc_gpio_en_o_3_;
  wire soc_gpio_en_o_4_;
  wire soc_gpio_en_o_5_;
  wire soc_gpio_en_o_6_;
  wire soc_gpio_en_o_7_;
  wire soc_gpio_en_o_8_;
  wire soc_gpio_en_o_9_;
  wire soc_gpio_i_0_;
  wire soc_gpio_i_10_;
  wire soc_gpio_i_11_;
  wire soc_gpio_i_12_;
  wire soc_gpio_i_13_;
  wire soc_gpio_i_14_;
  wire soc_gpio_i_15_;
  wire soc_gpio_i_1_;
  wire soc_gpio_i_2_;
  wire soc_gpio_i_3_;
  wire soc_gpio_i_4_;
  wire soc_gpio_i_5_;
  wire soc_gpio_i_6_;
  wire soc_gpio_i_7_;
  wire soc_gpio_i_8_;
  wire soc_gpio_i_9_;
  wire soc_gpio_ie_o_10_;
  wire soc_gpio_ie_o_11_;
  wire soc_gpio_ie_o_12_;
  wire soc_gpio_ie_o_13_;
  wire soc_gpio_ie_o_14_;
  wire soc_gpio_ie_o_15_;
  wire soc_gpio_ie_o_1_;
  wire soc_gpio_ie_o_2_;
  wire soc_gpio_ie_o_3_;
  wire soc_gpio_ie_o_4_;
  wire soc_gpio_ie_o_5_;
  wire soc_gpio_ie_o_6_;
  wire soc_gpio_ie_o_7_;
  wire soc_gpio_ie_o_8_;
  wire soc_gpio_ie_o_9_;
  wire soc_gpio_o_0_;
  wire soc_gpio_o_10_;
  wire soc_gpio_o_11_;
  wire soc_gpio_o_12_;
  wire soc_gpio_o_13_;
  wire soc_gpio_o_14_;
  wire soc_gpio_o_15_;
  wire soc_gpio_o_1_;
  wire soc_gpio_o_2_;
  wire soc_gpio_o_3_;
  wire soc_gpio_o_4_;
  wire soc_gpio_o_5_;
  wire soc_gpio_o_6_;
  wire soc_gpio_o_7_;
  wire soc_gpio_o_8_;
  wire soc_gpio_o_9_;
  wire soc_jtag_tck_i;
  wire soc_jtag_tdi_i;
  wire soc_jtag_tdo_o;
  wire soc_jtag_tms_i;
  wire soc_jtag_trst_ni;
  wire soc_osc_clk_i;
  wire soc_ref_clk_i;
  wire soc_rst_ni;
  wire soc_status_o;
  wire soc_uart_rx_i;
  wire soc_uart_tx_o;
  wire status_dummy;
  wire tdo_dummy;
  wire uart_tx_dummy;
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _02_ (
    .I(soc_gpio_en_o_14_),
    .ZN(soc_gpio_ie_o_14_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _03_ (
    .I(soc_gpio_en_o_15_),
    .ZN(soc_gpio_ie_o_15_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _04_ (
    .I(soc_gpio_en_o_1_),
    .ZN(soc_gpio_ie_o_1_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _05_ (
    .I(soc_gpio_en_o_2_),
    .ZN(soc_gpio_ie_o_2_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _06_ (
    .I(soc_gpio_en_o_3_),
    .ZN(soc_gpio_ie_o_3_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _07_ (
    .I(soc_gpio_en_o_4_),
    .ZN(soc_gpio_ie_o_4_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _08_ (
    .I(soc_gpio_en_o_5_),
    .ZN(soc_gpio_ie_o_5_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _09_ (
    .I(soc_gpio_en_o_6_),
    .ZN(soc_gpio_ie_o_6_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _10_ (
    .I(soc_gpio_en_o_7_),
    .ZN(soc_gpio_ie_o_7_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _11_ (
    .I(soc_gpio_en_o_8_),
    .ZN(soc_gpio_ie_o_8_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _12_ (
    .I(soc_gpio_en_o_9_),
    .ZN(soc_gpio_ie_o_9_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _13_ (
    .I(soc_gpio_en_o_10_),
    .ZN(soc_gpio_ie_o_10_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _14_ (
    .I(soc_gpio_en_o_11_),
    .ZN(soc_gpio_ie_o_11_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _15_ (
    .I(soc_gpio_en_o_12_),
    .ZN(soc_gpio_ie_o_12_)
  );
  gf180mcu_fd_sc_mcu7t5v0__inv_4 _16_ (
    .I(soc_gpio_en_o_13_),
    .ZN(soc_gpio_ie_o_13_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh _17_ (
    .Z(_00_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _18_ (
    .ZN(_01_)
  );
  croc_culp i_croc_soc (
    .clk_i(soc_clk_i),
    .fetch_en_i(soc_fetch_en_i),
    .gpio0_en_o(soc_gpio_en_o_0_),
    .gpio0_i(soc_gpio_i_0_),
    .gpio0_o(soc_gpio_o_0_),
    .gpio10_en_o(soc_gpio_en_o_10_),
    .gpio10_i(soc_gpio_i_10_),
    .gpio10_o(soc_gpio_o_10_),
    .gpio11_en_o(soc_gpio_en_o_11_),
    .gpio11_i(soc_gpio_i_11_),
    .gpio11_o(soc_gpio_o_11_),
    .gpio12_en_o(soc_gpio_en_o_12_),
    .gpio12_i(soc_gpio_i_12_),
    .gpio12_o(soc_gpio_o_12_),
    .gpio13_en_o(soc_gpio_en_o_13_),
    .gpio13_i(soc_gpio_i_13_),
    .gpio13_o(soc_gpio_o_13_),
    .gpio14_en_o(soc_gpio_en_o_14_),
    .gpio14_i(soc_gpio_i_14_),
    .gpio14_o(soc_gpio_o_14_),
    .gpio15_en_o(soc_gpio_en_o_15_),
    .gpio15_i(soc_gpio_i_15_),
    .gpio15_o(soc_gpio_o_15_),
    .gpio1_en_o(soc_gpio_en_o_1_),
    .gpio1_i(soc_gpio_i_1_),
    .gpio1_o(soc_gpio_o_1_),
    .gpio2_en_o(soc_gpio_en_o_2_),
    .gpio2_i(soc_gpio_i_2_),
    .gpio2_o(soc_gpio_o_2_),
    .gpio3_en_o(soc_gpio_en_o_3_),
    .gpio3_i(soc_gpio_i_3_),
    .gpio3_o(soc_gpio_o_3_),
    .gpio4_en_o(soc_gpio_en_o_4_),
    .gpio4_i(soc_gpio_i_4_),
    .gpio4_o(soc_gpio_o_4_),
    .gpio5_en_o(soc_gpio_en_o_5_),
    .gpio5_i(soc_gpio_i_5_),
    .gpio5_o(soc_gpio_o_5_),
    .gpio6_en_o(soc_gpio_en_o_6_),
    .gpio6_i(soc_gpio_i_6_),
    .gpio6_o(soc_gpio_o_6_),
    .gpio7_en_o(soc_gpio_en_o_7_),
    .gpio7_i(soc_gpio_i_7_),
    .gpio7_o(soc_gpio_o_7_),
    .gpio8_en_o(soc_gpio_en_o_8_),
    .gpio8_i(soc_gpio_i_8_),
    .gpio8_o(soc_gpio_o_8_),
    .gpio9_en_o(soc_gpio_en_o_9_),
    .gpio9_i(soc_gpio_i_9_),
    .gpio9_o(soc_gpio_o_9_),
    .jtag_tck_i(soc_jtag_tck_i),
    .jtag_tdi_i(soc_jtag_tdi_i),
    .jtag_tdo_o(soc_jtag_tdo_o),
    .jtag_tms_i(soc_jtag_tms_i),
    .jtag_trst_ni(soc_jtag_trst_ni),
    .ref_clk_i(soc_ref_clk_i),
    .rst_ni(soc_rst_ni),
    .status_o(soc_status_o),
    .uart_rx_i(soc_uart_rx_i),
    .uart_tx_o(soc_uart_tx_o)
  );
  gf180mcu_fd_io__asig_5p0 pad_adc_inn_i (
    .ASIG5V(adc_inn_i),
    .DVDD(VDD),
    .DVSS(VSS),
    .VDD(VDD),
    .VSS(VSS)
  );
  gf180mcu_fd_io__asig_5p0 pad_adc_inp_i (
    .ASIG5V(adc_inp_i),
    .DVDD(VDD),
    .DVSS(VSS),
    .VDD(VDD),
    .VSS(VSS)
  );
  gf180mcu_fd_io__in_c pad_clk_i (
    .DVDD(VDD),
    .DVSS(VSS),
    .PAD(clk_i),
    .PD(_00_),
    .PU(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_clk_i)
  );
  gf180mcu_fd_io__asig_5p0 pad_dac_outn_o (
    .ASIG5V(dac_outn_o),
    .DVDD(VDD),
    .DVSS(VSS),
    .VDD(VDD),
    .VSS(VSS)
  );
  gf180mcu_fd_io__asig_5p0 pad_dac_outp_o (
    .ASIG5V(dac_outp_o),
    .DVDD(VDD),
    .DVSS(VSS),
    .VDD(VDD),
    .VSS(VSS)
  );
  gf180mcu_fd_io__asig_5p0 pad_dac_vbias_i (
    .ASIG5V(dac_vbias_i),
    .DVDD(VDD),
    .DVSS(VSS),
    .VDD(VDD),
    .VSS(VSS)
  );
  gf180mcu_fd_io__in_c pad_fetch_en_i (
    .DVDD(VDD),
    .DVSS(VSS),
    .PAD(fetch_en_i),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_fetch_en_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio0_io (
    .A(soc_gpio_o_0_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_en_o_0_),
    .OE(soc_gpio_en_o_0_),
    .PAD(gpio0_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_0_)
  );
  gf180mcu_fd_io__bi_t pad_gpio10_io (
    .A(soc_gpio_o_10_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_10_),
    .OE(soc_gpio_en_o_10_),
    .PAD(gpio10_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_10_)
  );
  gf180mcu_fd_io__bi_t pad_gpio11_io (
    .A(soc_gpio_o_11_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_11_),
    .OE(soc_gpio_en_o_11_),
    .PAD(gpio11_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_11_)
  );
  gf180mcu_fd_io__bi_t pad_gpio12_io (
    .A(soc_gpio_o_12_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_12_),
    .OE(soc_gpio_en_o_12_),
    .PAD(gpio12_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_12_)
  );
  gf180mcu_fd_io__bi_t pad_gpio13_io (
    .A(soc_gpio_o_13_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_13_),
    .OE(soc_gpio_en_o_13_),
    .PAD(gpio13_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_13_)
  );
  gf180mcu_fd_io__bi_t pad_gpio14_io (
    .A(soc_gpio_o_14_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_14_),
    .OE(soc_gpio_en_o_14_),
    .PAD(gpio14_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_14_)
  );
  gf180mcu_fd_io__bi_t pad_gpio15_io (
    .A(soc_gpio_o_15_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_15_),
    .OE(soc_gpio_en_o_15_),
    .PAD(gpio15_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_15_)
  );
  gf180mcu_fd_io__bi_t pad_gpio1_io (
    .A(soc_gpio_o_1_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_1_),
    .OE(soc_gpio_en_o_1_),
    .PAD(gpio1_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_1_)
  );
  gf180mcu_fd_io__bi_t pad_gpio2_io (
    .A(soc_gpio_o_2_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_2_),
    .OE(soc_gpio_en_o_2_),
    .PAD(gpio2_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_2_)
  );
  gf180mcu_fd_io__bi_t pad_gpio3_io (
    .A(soc_gpio_o_3_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_3_),
    .OE(soc_gpio_en_o_3_),
    .PAD(gpio3_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_3_)
  );
  gf180mcu_fd_io__bi_t pad_gpio4_io (
    .A(soc_gpio_o_4_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_4_),
    .OE(soc_gpio_en_o_4_),
    .PAD(gpio4_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_4_)
  );
  gf180mcu_fd_io__bi_t pad_gpio5_io (
    .A(soc_gpio_o_5_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_5_),
    .OE(soc_gpio_en_o_5_),
    .PAD(gpio5_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_5_)
  );
  gf180mcu_fd_io__bi_t pad_gpio6_io (
    .A(soc_gpio_o_6_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_6_),
    .OE(soc_gpio_en_o_6_),
    .PAD(gpio6_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_6_)
  );
  gf180mcu_fd_io__bi_t pad_gpio7_io (
    .A(soc_gpio_o_7_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_7_),
    .OE(soc_gpio_en_o_7_),
    .PAD(gpio7_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_7_)
  );
  gf180mcu_fd_io__bi_t pad_gpio8_io (
    .A(soc_gpio_o_8_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_8_),
    .OE(soc_gpio_en_o_8_),
    .PAD(gpio8_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_8_)
  );
  gf180mcu_fd_io__bi_t pad_gpio9_io (
    .A(soc_gpio_o_9_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(soc_gpio_ie_o_9_),
    .OE(soc_gpio_en_o_9_),
    .PAD(gpio9_io),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_gpio_i_9_)
  );
  gf180mcu_fd_io__in_c pad_jtag_tck_i (
    .DVDD(VDD),
    .DVSS(VSS),
    .PAD(jtag_tck_i),
    .PD(_00_),
    .PU(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_jtag_tck_i)
  );
  gf180mcu_fd_io__in_c pad_jtag_tdi_i (
    .DVDD(VDD),
    .DVSS(VSS),
    .PAD(jtag_tdi_i),
    .PD(_00_),
    .PU(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_jtag_tdi_i)
  );
  gf180mcu_fd_io__bi_t pad_jtag_tdo_o (
    .A(soc_jtag_tdo_o),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(_01_),
    .OE(_00_),
    .PAD(jtag_tdo_o),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(tdo_dummy)
  );
  gf180mcu_fd_io__in_c pad_jtag_tms_i (
    .DVDD(VDD),
    .DVSS(VSS),
    .PAD(jtag_tms_i),
    .PD(_00_),
    .PU(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_jtag_tms_i)
  );
  gf180mcu_fd_io__in_c pad_jtag_trst_ni (
    .DVDD(VDD),
    .DVSS(VSS),
    .PAD(jtag_trst_ni),
    .PD(_00_),
    .PU(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_jtag_trst_ni)
  );
  gf180mcu_fd_io__in_c pad_osc_clk_i (
    .DVDD(VDD),
    .DVSS(VSS),
    .PAD(osc_clk_i),
    .PD(_00_),
    .PU(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_osc_clk_i)
  );
  gf180mcu_fd_io__bi_t pad_pll_clk_o (
    .A(_01_),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(_01_),
    .OE(_00_),
    .PAD(pll_clk_o),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(pll_clk_dummy)
  );
  gf180mcu_fd_io__in_c pad_ref_clk_i (
    .DVDD(VDD),
    .DVSS(VSS),
    .PAD(ref_clk_i),
    .PD(_00_),
    .PU(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_ref_clk_i)
  );
  gf180mcu_fd_io__in_c pad_rst_ni (
    .DVDD(VDD),
    .DVSS(VSS),
    .PAD(rst_ni),
    .PD(_00_),
    .PU(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_rst_ni)
  );
  gf180mcu_fd_io__bi_t pad_status_o (
    .A(soc_status_o),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(_01_),
    .OE(_00_),
    .PAD(status_o),
    .PD(_00_),
    .PU(_01_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(status_dummy)
  );
  gf180mcu_fd_io__in_c pad_uart_rx_i (
    .DVDD(VDD),
    .DVSS(VSS),
    .PAD(uart_rx_i),
    .PD(_01_),
    .PU(_00_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(soc_uart_rx_i)
  );
  gf180mcu_fd_io__bi_t pad_uart_tx_o (
    .A(soc_uart_tx_o),
    .CS(_01_),
    .DVDD(VDD),
    .DVSS(VSS),
    .IE(_01_),
    .OE(_00_),
    .PAD(uart_tx_o),
    .PD(_01_),
    .PU(_00_),
    .SL(_01_),
    .VDD(VDD),
    .VSS(VSS),
    .Y(uart_tx_dummy)
  );
  gf180mcu_fd_io__dvdd pad_vdd0 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VSS(VSS)
  );
  gf180mcu_fd_io__dvdd pad_vdd1 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VSS(VSS)
  );
  gf180mcu_fd_io__dvdd pad_vdd2 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VSS(VSS)
  );
  gf180mcu_fd_io__dvdd pad_vdd3 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VSS(VSS)
  );
  gf180mcu_fd_io__dvdd pad_vddio0 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VSS(VSS)
  );
  gf180mcu_fd_io__dvdd pad_vddio1 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VSS(VSS)
  );
  gf180mcu_fd_io__dvdd pad_vddio2 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VSS(VSS)
  );
  gf180mcu_fd_io__dvdd pad_vddio3 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VSS(VSS)
  );
  gf180mcu_fd_io__dvss pad_vss0 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VDD(VDD)
  );
  gf180mcu_fd_io__dvss pad_vss1 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VDD(VDD)
  );
  gf180mcu_fd_io__dvss pad_vss2 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VDD(VDD)
  );
  gf180mcu_fd_io__dvss pad_vss3 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VDD(VDD)
  );
  gf180mcu_fd_io__dvss pad_vssio0 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VDD(VDD)
  );
  gf180mcu_fd_io__dvss pad_vssio1 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VDD(VDD)
  );
  gf180mcu_fd_io__dvss pad_vssio2 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VDD(VDD)
  );
  gf180mcu_fd_io__dvss pad_vssio3 (
    .DVDD(VDD),
    .DVSS(VSS),
    .VDD(VDD)
  );
endmodule
