/* Generated by Yosys 0.57+72 (git sha1 fa02d71f6, x86_64-conda-linux-gnu-c++ 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/home/runner/work/conda-opensource-eda/conda-opensource-eda/workdir/conda-env/conda-bld/yosys_1757723646908/work=/usr/local/src/conda/yosys-0.57_73_gfa02d71f6 -fdebug-prefix-map=/home/admin/conda/envs/croc-py312=/usr/local/src/conda-prefix -fPIC -O3) */

module croc_culp_chip(clk_i, rst_ni, ref_clk_i, jtag_tck_i, jtag_trst_ni, jtag_tms_i, jtag_tdi_i, jtag_tdo_o, uart_rx_i, uart_tx_o, fetch_en_i, status_o, gpio0_io, gpio1_io, gpio2_io, gpio3_io, gpio4_io, gpio5_io, gpio6_io, gpio7_io, gpio8_io
, gpio9_io, gpio10_io, gpio11_io, gpio12_io, gpio13_io, gpio14_io, gpio15_io, pll_clk_o, osc_clk_i);
  input clk_i;
  wire clk_i;
  input rst_ni;
  wire rst_ni;
  input ref_clk_i;
  wire ref_clk_i;
  input jtag_tck_i;
  wire jtag_tck_i;
  input jtag_trst_ni;
  wire jtag_trst_ni;
  input jtag_tms_i;
  wire jtag_tms_i;
  input jtag_tdi_i;
  wire jtag_tdi_i;
  output jtag_tdo_o;
  wire jtag_tdo_o;
  input uart_rx_i;
  wire uart_rx_i;
  output uart_tx_o;
  wire uart_tx_o;
  input fetch_en_i;
  wire fetch_en_i;
  output status_o;
  wire status_o;
  inout gpio0_io;
  wire gpio0_io;
  inout gpio1_io;
  wire gpio1_io;
  inout gpio2_io;
  wire gpio2_io;
  inout gpio3_io;
  wire gpio3_io;
  inout gpio4_io;
  wire gpio4_io;
  inout gpio5_io;
  wire gpio5_io;
  inout gpio6_io;
  wire gpio6_io;
  inout gpio7_io;
  wire gpio7_io;
  inout gpio8_io;
  wire gpio8_io;
  inout gpio9_io;
  wire gpio9_io;
  inout gpio10_io;
  wire gpio10_io;
  inout gpio11_io;
  wire gpio11_io;
  inout gpio12_io;
  wire gpio12_io;
  inout gpio13_io;
  wire gpio13_io;
  inout gpio14_io;
  wire gpio14_io;
  inout gpio15_io;
  wire gpio15_io;
  output pll_clk_o;
  wire pll_clk_o;
  input osc_clk_i;
  wire osc_clk_i;
  wire _0_;
  wire _1_;
  wire adc_inn_i;
  wire adc_inp_i;
  wire dac_outn_o;
  wire dac_outp_o;
  wire dac_vbias_i;
  wire pll_clk_dummy;
  wire soc_clk_i;
  wire soc_fetch_en_i;
  wire soc_gpio0_i;
  wire soc_gpio10_i;
  wire soc_gpio11_i;
  wire soc_gpio12_i;
  wire soc_gpio13_i;
  wire soc_gpio14_i;
  wire soc_gpio15_i;
  wire soc_gpio1_i;
  wire soc_gpio2_i;
  wire soc_gpio3_i;
  wire soc_gpio4_i;
  wire soc_gpio5_i;
  wire soc_gpio6_i;
  wire soc_gpio7_i;
  wire soc_gpio8_i;
  wire soc_gpio9_i;
  wire soc_gpio_o_0_;
  wire soc_gpio_o_10_;
  wire soc_gpio_o_11_;
  wire soc_gpio_o_12_;
  wire soc_gpio_o_13_;
  wire soc_gpio_o_14_;
  wire soc_gpio_o_15_;
  wire soc_gpio_o_1_;
  wire soc_gpio_o_2_;
  wire soc_gpio_o_3_;
  wire soc_gpio_o_4_;
  wire soc_gpio_o_5_;
  wire soc_gpio_o_6_;
  wire soc_gpio_o_7_;
  wire soc_gpio_o_8_;
  wire soc_gpio_o_9_;
  wire soc_gpio_out_en_o_0_;
  wire soc_gpio_out_en_o_10_;
  wire soc_gpio_out_en_o_11_;
  wire soc_gpio_out_en_o_12_;
  wire soc_gpio_out_en_o_13_;
  wire soc_gpio_out_en_o_14_;
  wire soc_gpio_out_en_o_15_;
  wire soc_gpio_out_en_o_1_;
  wire soc_gpio_out_en_o_2_;
  wire soc_gpio_out_en_o_3_;
  wire soc_gpio_out_en_o_4_;
  wire soc_gpio_out_en_o_5_;
  wire soc_gpio_out_en_o_6_;
  wire soc_gpio_out_en_o_7_;
  wire soc_gpio_out_en_o_8_;
  wire soc_gpio_out_en_o_9_;
  wire soc_jtag_tck_i;
  wire soc_jtag_tdi_i;
  wire soc_jtag_tdo_o;
  wire soc_jtag_tms_i;
  wire soc_jtag_trst_ni;
  wire soc_osc_clk_i;
  wire soc_ref_clk_i;
  wire soc_rst_ni;
  wire soc_status_o;
  wire soc_uart_rx_i;
  wire soc_uart_tx_o;
  wire status_dummy;
  wire tdo_dummy;
  wire uart_tx_dummy;
  gf180mcu_fd_sc_mcu7t5v0__tieh _2_ (
    .Z(_0_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _3_ (
    .ZN(_1_)
  );
  croc_culp i_croc_soc (
    .clk_i(soc_clk_i),
    .fetch_en_i(soc_fetch_en_i),
    .gpio0_en_o(soc_gpio_out_en_o_0_),
    .gpio0_i(_1_),
    .gpio0_o(soc_gpio_o_0_),
    .gpio10_en_o(soc_gpio_out_en_o_10_),
    .gpio10_i(_1_),
    .gpio10_o(soc_gpio_o_10_),
    .gpio11_en_o(soc_gpio_out_en_o_11_),
    .gpio11_i(_1_),
    .gpio11_o(soc_gpio_o_11_),
    .gpio12_en_o(soc_gpio_out_en_o_12_),
    .gpio12_i(_1_),
    .gpio12_o(soc_gpio_o_12_),
    .gpio13_en_o(soc_gpio_out_en_o_13_),
    .gpio13_i(_1_),
    .gpio13_o(soc_gpio_o_13_),
    .gpio14_en_o(soc_gpio_out_en_o_14_),
    .gpio14_i(_1_),
    .gpio14_o(soc_gpio_o_14_),
    .gpio15_en_o(soc_gpio_out_en_o_15_),
    .gpio15_i(_1_),
    .gpio15_o(soc_gpio_o_15_),
    .gpio1_en_o(soc_gpio_out_en_o_1_),
    .gpio1_i(_1_),
    .gpio1_o(soc_gpio_o_1_),
    .gpio2_en_o(soc_gpio_out_en_o_2_),
    .gpio2_i(_1_),
    .gpio2_o(soc_gpio_o_2_),
    .gpio3_en_o(soc_gpio_out_en_o_3_),
    .gpio3_i(_1_),
    .gpio3_o(soc_gpio_o_3_),
    .gpio4_en_o(soc_gpio_out_en_o_4_),
    .gpio4_i(_1_),
    .gpio4_o(soc_gpio_o_4_),
    .gpio5_en_o(soc_gpio_out_en_o_5_),
    .gpio5_i(_1_),
    .gpio5_o(soc_gpio_o_5_),
    .gpio6_en_o(soc_gpio_out_en_o_6_),
    .gpio6_i(_1_),
    .gpio6_o(soc_gpio_o_6_),
    .gpio7_en_o(soc_gpio_out_en_o_7_),
    .gpio7_i(_1_),
    .gpio7_o(soc_gpio_o_7_),
    .gpio8_en_o(soc_gpio_out_en_o_8_),
    .gpio8_i(_1_),
    .gpio8_o(soc_gpio_o_8_),
    .gpio9_en_o(soc_gpio_out_en_o_9_),
    .gpio9_i(_1_),
    .gpio9_o(soc_gpio_o_9_),
    .jtag_tck_i(soc_jtag_tck_i),
    .jtag_tdi_i(soc_jtag_tdi_i),
    .jtag_tdo_o(soc_jtag_tdo_o),
    .jtag_tms_i(soc_jtag_tms_i),
    .jtag_trst_ni(soc_jtag_trst_ni),
    .ref_clk_i(soc_ref_clk_i),
    .rst_ni(soc_rst_ni),
    .status_o(soc_status_o),
    .uart_rx_i(soc_uart_rx_i),
    .uart_tx_o(soc_uart_tx_o)
  );
  gf180mcu_fd_io__asig_5p0 pad_adc_inn_i (
    .ASIG5V(adc_inn_i)
  );
  gf180mcu_fd_io__asig_5p0 pad_adc_inp_i (
    .ASIG5V(adc_inp_i)
  );
  gf180mcu_fd_io__in_c pad_clk_i (
    .PAD(clk_i),
    .PD(_0_),
    .PU(_1_),
    .Y(soc_clk_i)
  );
  gf180mcu_fd_io__asig_5p0 pad_dac_outn_o (
    .ASIG5V(dac_outn_o)
  );
  gf180mcu_fd_io__asig_5p0 pad_dac_outp_o (
    .ASIG5V(dac_outp_o)
  );
  gf180mcu_fd_io__asig_5p0 pad_dac_vbias_i (
    .ASIG5V(dac_vbias_i)
  );
  gf180mcu_fd_io__in_c pad_fetch_en_i (
    .PAD(fetch_en_i),
    .Y(soc_fetch_en_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio0_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio0_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio0_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio10_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio10_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio10_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio11_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio11_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio11_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio12_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio12_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio12_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio13_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio13_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio13_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio14_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio14_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio14_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio15_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio15_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio15_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio1_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio1_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio1_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio2_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio2_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio2_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio3_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio3_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio3_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio4_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio4_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio4_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio5_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio5_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio5_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio6_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio6_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio6_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio7_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio7_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio7_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio8_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio8_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio8_i)
  );
  gf180mcu_fd_io__bi_t pad_gpio9_io (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_1_),
    .PAD(gpio9_io),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(soc_gpio9_i)
  );
  gf180mcu_fd_io__in_c pad_jtag_tck_i (
    .PAD(jtag_tck_i),
    .PD(_0_),
    .PU(_1_),
    .Y(soc_jtag_tck_i)
  );
  gf180mcu_fd_io__in_c pad_jtag_tdi_i (
    .PAD(jtag_tdi_i),
    .PD(_0_),
    .PU(_1_),
    .Y(soc_jtag_tdi_i)
  );
  gf180mcu_fd_io__bi_t pad_jtag_tdo_o (
    .A(soc_jtag_tdo_o),
    .CS(_1_),
    .IE(_1_),
    .OE(_0_),
    .PAD(jtag_tdo_o),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(tdo_dummy)
  );
  gf180mcu_fd_io__in_c pad_jtag_tms_i (
    .PAD(jtag_tms_i),
    .PD(_0_),
    .PU(_1_),
    .Y(soc_jtag_tms_i)
  );
  gf180mcu_fd_io__in_c pad_jtag_trst_ni (
    .PAD(jtag_trst_ni),
    .PD(_0_),
    .PU(_1_),
    .Y(soc_jtag_trst_ni)
  );
  gf180mcu_fd_io__in_c pad_osc_clk_i (
    .PAD(osc_clk_i),
    .PD(_0_),
    .PU(_1_),
    .Y(soc_osc_clk_i)
  );
  gf180mcu_fd_io__bi_t pad_pll_clk_o (
    .A(_1_),
    .CS(_1_),
    .IE(_1_),
    .OE(_0_),
    .PAD(pll_clk_o),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(pll_clk_dummy)
  );
  gf180mcu_fd_io__in_c pad_ref_clk_i (
    .PAD(ref_clk_i),
    .PD(_0_),
    .PU(_1_),
    .Y(soc_ref_clk_i)
  );
  gf180mcu_fd_io__in_c pad_rst_ni (
    .PAD(rst_ni),
    .PD(_0_),
    .PU(_1_),
    .Y(soc_rst_ni)
  );
  gf180mcu_fd_io__bi_t pad_status_o (
    .A(soc_status_o),
    .CS(_1_),
    .IE(_1_),
    .OE(_0_),
    .PAD(status_o),
    .PD(_0_),
    .PU(_1_),
    .SL(_1_),
    .Y(status_dummy)
  );
  gf180mcu_fd_io__in_c pad_uart_rx_i (
    .PAD(uart_rx_i),
    .PD(_1_),
    .PU(_0_),
    .Y(soc_uart_rx_i)
  );
  gf180mcu_fd_io__bi_t pad_uart_tx_o (
    .A(soc_uart_tx_o),
    .CS(_1_),
    .IE(_1_),
    .OE(_0_),
    .PAD(uart_tx_o),
    .PD(_1_),
    .PU(_0_),
    .SL(_1_),
    .Y(uart_tx_dummy)
  );
  gf180mcu_fd_io__dvdd pad_vdd0 (
  );
  gf180mcu_fd_io__dvdd pad_vdd1 (
  );
  gf180mcu_fd_io__dvdd pad_vdd2 (
  );
  gf180mcu_fd_io__dvdd pad_vdd3 (
  );
  gf180mcu_fd_io__dvdd pad_vddio0 (
  );
  gf180mcu_fd_io__dvdd pad_vddio1 (
  );
  gf180mcu_fd_io__dvdd pad_vddio2 (
  );
  gf180mcu_fd_io__dvdd pad_vddio3 (
  );
  gf180mcu_fd_io__dvss pad_vss0 (
  );
  gf180mcu_fd_io__dvss pad_vss1 (
  );
  gf180mcu_fd_io__dvss pad_vss2 (
  );
  gf180mcu_fd_io__dvss pad_vss3 (
  );
  gf180mcu_fd_io__dvss pad_vssio0 (
  );
  gf180mcu_fd_io__dvss pad_vssio1 (
  );
  gf180mcu_fd_io__dvss pad_vssio2 (
  );
  gf180mcu_fd_io__dvss pad_vssio3 (
  );
endmodule
